Web/CIMBypass/Controllers/ActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Enel.Indra.CIMBypass.Business.Service;
using Enel.Indra.CIMBypass.Business.Data.Model.Entity;
using Microsoft.AspNetCore.Mvc;
using Enel.Indra.CIMBypass.Models.Action;
using Newtonsoft.Json;
using Enel.Indra.CIMBypass.Business.Common.Log;
using Enel.Indra.CIMBypass.Models.Common;

namespace Enel.Indra.CIMBypass.Controllers
{
    public class ActionController : BaseController
    {

        private readonly Log4NetLogger _Logger = new Log4NetLogger("ActionController");
        private IActionService _Service;

        public ActionController(IActionService IActionService) {
            this._Service = IActionService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            _Logger.DebugOut(nameof(Index), "NO PARAMETER");

            IndexVModel modello = new IndexVModel();
            List<CatFlussiModel> elencoFlussiAttvi = _Service.PrelevaElencoFlussiAttivi();
            modello.InizializzaElencoFlussi(elencoFlussiAttvi);

            return View(modello);
        }
        
        [HttpPost]
        public IActionResult PrelevaElencoFileDaElaborare() {
            _Logger.DebugIn(nameof(PrelevaElencoFileDaElaborare), "NO PARAMETER");

            List<ArchivioFileModel> fileDaElaborare = _Service.PrelevaElencoFileDaElaborare();

            _Logger.DebugOut(nameof(PrelevaElencoFileDaElaborare), "fileDaElaborare: " + Json(fileDaElaborare).ToString());

            return Json(fileDaElaborare);
        }

        [HttpPost]
        public IActionResult PrelevaElencoFileElaborati()
        {
            _Logger.DebugIn(nameof(PrelevaElencoFileElaborati), "NO PARAMETER");

            List<ArchivioFileModel> fileElaborati = _Service.PrelevaElencoFileElaborati();

            _Logger.DebugOut(nameof(PrelevaElencoFileElaborati), "fileElaborati: " + Json(fileElaborati).ToString());

            return Json(fileElaborati);
        }

        [HttpGet]
        public IActionResult ElaboraFileInput(string idArchivio)
        {
            _Logger.DebugOut(nameof(ElaboraFileInput), "idArchivio: " + idArchivio);

            _Service.SalvaInTabella(Int32.Parse(idArchivio));

            return Json(true);
        }
    }
}

Web/CIMBypass/Views/Shared/_ConfirmationPopup.cshtml
<!-- modal next step -->
<div class="modal fade" id="configModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog dialog-step" role="document">
        <div class="box box-primary">
            <div class="box-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="modal-header">
                    <h5 class="modal-title scarti-title" id="exampleModalLabel">Sei sicuro di voler procedere ?</h5>
                </div>
                <div class="modal-body">
                    &nbsp;
                </div>
                <div class="modal-footer no-border">
                    <button type="button" class="button-cancel-enel pull-left" data-dismiss="modal"><i class="fa fa-close"></i> Annulla</button>
                    <button type="button" class="button-main-enel pull-right">Continua <i class="fa fa-chevron-right"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--  modal next step -->

<script></script>

Web/CIMBypass/Views/Shared/_Header.cshtml
<header class="main-header">
    <!-- Logo -->
    <a href="@Url.Action("Index","Home")" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">ENEL</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><img src="~/Content/images/enel-logo.png" alt="SMaRT" height="48" /></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
    </nav>
</header>

Web/CIMBypass/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title - CIMBypass</title>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="~/Content/dist/css/AdminLTE.css" rel="stylesheet" />
    <link href="~/Content/dist/css/Indra.css" rel="stylesheet" />
    <link href="~/Content/dist/css/Enel-main.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/fontawesome-free-5.7.2-web/css/all.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/datatables/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/plugins/datepicker/datepicker3.css" rel="stylesheet" />
    <link href="~/Content/dist/css/skins/_all-skins.css" rel="stylesheet" />
    <script src="~/Scripts/plugins/jQuery/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/plugins/datepicker/locales/bootstrap-datepicker.it.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/controller/shared.logger.js"></script>
    <script src="~/Scripts/controller/shared.spinner.js"></script>
    <script src="~/Scripts/controller/shared.validator.js"></script>
    <script src="~/Scripts/controller/shared.js"></script>
    <script src="~/Content/dist/js/app.js"></script>
</head>
<body class="hold-transition skin-rose sidebar-mini">
    <div class="wrapper" height auto; min-height 100%;>
        @Html.Partial("_Header")

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            @Html.Partial("_NavMenu")
        </aside>
        <div class="content-wrapper">
            @Html.Partial("_Message")
            @RenderBody()
        </div>
        <footer class="main-footer">
            <div class="footer-welcome-user pull-left welcome-text user-decoration">
                Benvenuto utente
            </div>
            <div class="pull-left col-md-offset-4 logo-footer-enel" style="color:transparent">
                <i class="fas fa-ghost"></i>Sei in @ViewBag.Envirorment<i class="fas fa-ghost"></i>
            </div>
            <div class="pull-right hidden-xs">
                CIMBypass - @DateTime.Now.Year <i class="fas fa-copyright"></i>
            </div>
            <span>&nbsp;</span>
        </footer>
    </div>
</body>
</html>

Web/CIMBypass/Views/Shared/_Message.cshtml
@using Enel.Indra.CIMBypass.Business.Data.Model.CustomModel;


@if (TempData["OperationResult"] != null)
{
    OperationResultModel msgMdl = (OperationResultModel)TempData["OperationResult"];
    <section class="contentMessage">
        <div id="divMessageTransaction" class="msg msg--@msgMdl.Type msg--@msgMdl.Type-text ">
            <i class="icon fa fa-@msgMdl.IconName"></i>
            @msgMdl.Message
        </div>
    </section>
}

<script>
    $(document).ready(function () {
        //$('#divMessageTransaction').show();
        $('#divMessageTransaction').fadeIn(1500).delay(2000).fadeOut(1500); //10 seconds x 1000 milisec = 5000 milisec
    });
</script>

Web/CIMBypass/Views/Shared/_NavMenu.cshtml
<section class="sidebar">
    <ul class="sidebar-menu">
        @{
            var controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
            var actionName = this.ViewContext.RouteData.Values["action"].ToString();
        }
        <li class="treeview @(controllerName == "Upload" && actionName == "UploadFile"  ? "active" : "")">
            <a href="@Url.Action("UploadFile", "Upload")">
                <i class="fas fa-cloud-upload-alt"></i> <span>Upload</span>
            </a>
        </li>
        <li class="treeview @(controllerName == "Mock" && actionName == "mockMethod" ? "active" : "")">
            <a href="@Url.Action("Index", "Action")">
                <i class="fas fa-piggy-bank"></i> <span>Action</span>
            </a>
        </li>
        <!--
        <li class="treeview @@(controllerName == "Mock" ? "active" : "")">
            <a href="@@Url.Action("mockMethod", "Mock")">
                <i class="fa fa-cogs"></i> <span>Impostazioni</span>
            </a>
        </li>
        -->
        <li class="treeview @(controllerName == "Help" ? "active" : "" )">
            <a href="#">
                <i class="fa fa-question-circle"></i> <span>Help</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li class="@(actionName == "Upload" ? "active" : "")">
                    <a href="@Url.Action("mockMethod","Help")">
                        <i class="fa fa-info-circle"></i>
                        <span>
                            Upload
                        </span>
                    </a>
                </li>
                <li class="@(actionName == "mockMethod" ? "active" : "")">
                    <a href="@Url.Action("Action","Help")">
                        <i class="fa fa-info-circle"></i>
                        <span>
                            Action
                        </span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</section>